version: "3"
services:
  cs16:
    image: vuthaihoc/cs16:latest
    ports:
     - "27015:27015"
     - "27015:27015/udp"
    restart: always
    environment:
     - START_MAP=fy_snow_dew
     - MAXPLAYERS=32
     - SERVER_NAME=VNP-CS1.6
     - START_MONEY=16000
     - FRIENDLY_FIRE=1
